name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build release APK and AAB after test
      run: |
        ./gradlew test
        ./gradlew assembleRelease
        ./gradlew bundleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3.1.0
      with:
          name: app-release.apk

    - name: Upload AAB Bundle
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app-release.aab
